### ISSUE TITLE
Event memory and FPS issues

### ISSUE THREAD

**Issue by Victorma** [Victorma/IsoUnity#18]
Testes have shown that using controller to move character causes a FPS down, and extended over time it causes a constant FPS lose.
For being ScriptableObject, events should be destroyed after being used. 
Making them normal object (System.Object) will cause garbage collector deleting them. On the other hand, Serialization may be affected.
We've to discuss and study options before we're sure about this.

**Comment by Victormafire** [comment]
Related #58

**Comment by Victorma** [comment]
This fix was made a long ago when SerializableGameEvent and GameEvent implementations were made.
GameEvents implement System.Object as SerializableGameEvent implement UnityEngine.Object.
Both, however, implement IGameEvent interface.
