### ISSUE TITLE
We cannot restart a IsoUnity scene

### ISSUE THREAD

**Issue by federicopeinado** [Victorma/IsoUnity#33]
Porque se mueren los objetos delegados o algo así... el caso es que arranca en fondo negro si intentas rejugar el juego tras haber sacado un Game Over :-(

**Comment by Victormafire** [comment]
Este bug creo que se produce al recargar la escena y regenerar el objeto Game. Dado que la instancia se regenera pero los mánagers (Secuence, Animator...) solo se generan la primera vez se pierden las referencias.
