### ISSUE TITLE
Some lines appears between cells when moving in a large map

### ISSUE THREAD

**Issue by federicopeinado** [Victorma/IsoUnity#39]
It happens in IsoAbbey, not sure if it is a failure of IsoUnity, Unity, something that we can avoid or not... ¿?

**Comment by Victormafire** [comment]
Can I see a picture, a video or maybe a live demo? (in the current version of IsoAbbey it happens?)

**Comment by Victorma** [comment]
There have been recent case of this and the reason was related to bad texture borders (i.e. transparency).
However, this might be reopened in case the problem appears on texture mappings.
